// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// mc_sensitivity_op
arma::sp_mat mc_sensitivity_op(List products);
RcppExport SEXP _mcglm_mc_sensitivity_op(SEXP productsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type products(productsSEXP);
    rcpp_result_gen = Rcpp::wrap(mc_sensitivity_op(products));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mcglm_mc_sensitivity_op", (DL_FUNC) &_mcglm_mc_sensitivity_op, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_mcglm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
