# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mc_sensitivity_op <- function(products) {
    .Call('_mcglm_mc_sensitivity_op', PACKAGE = 'mcglm', products)
}

