# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mc_sensitivity_op <- function(products) {
    .Call('_mcglm_mc_sensitivity_op', PACKAGE = 'mcglm', products)
}

mc_variability_op <- function(sensitivity, W, k4) {
    .Call('_mcglm_mc_variability_op', PACKAGE = 'mcglm', sensitivity, W, k4)
}

